service: aws-lambda-gis-indexer
provider:
  name: aws
  runtime: nodejs22.x
functions:
  gisIndexer:
    handler: dist/lambda.handler
    events:
      - http:
          path: hello
          method: get
