packages:
  - packages/*
  - sites/*
overrides:
  '@types/node': '22.19.10'
  'zod': '^4.0.8'
allowBuilds:
  '@parcel/watcher': true
  '@vaadin/vaadin-usage-statistics': true
  sharp: true
  unrs-resolver: true
