name: Trigger Amplify Build for widgets`

on:
  push:
    branches:
      - main
    paths:
      - sites/widgets/**
      - packages/sdk/**
      - packages/ui/**
      - packages/tw-config/**
      - .github/deploy-widgets.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ci-${{github.ref}}
      cancel-in-progress: false
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AMPLIFY_DEPLOYER_ROLE }}
          role-session-name: github-actions-deploy-widgets-session
          aws-region: us-east-2

      - name: Trigger AWS Amplify Build
        run: |
          aws amplify start-job --app-id d1wvh0ssryavqz --branch-name main --job-type RELEASE
