name: Trigger Amplify Build for widgets`

on:
  push:
    branches:
      - main
    paths:
      - sites/widgets/**
      - packages/sdk/**
      - packages/ui/**
      - packages/tw-config/**
      - .github/deploy-widgets.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ci-${{github.ref}}
      cancel-in-progress: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2 # Update this if your Amplify app is in a different region

      - name: Trigger AWS Amplify Build
        run: |
          aws amplify start-job --app-id d1wvh0ssryavqz --branch-name main --job-type RELEASE
