name: Trigger Amplify Build for msb

on:
  push:
    branches:
      - main
    paths:
      - sites/msb/**
      - packages/sdk/**
      - packages/ui/**
      - packages/tw-config/**
      - .github/workflows/deploy-msb.yml

jobs:
  deploy:
    concurrency:
      group: ci-${{github.ref}}
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2 # Update this if your Amplify app is in a different region

      - name: Trigger AWS Amplify Build
        run: |
          aws amplify start-job \
            --app-id d2hc61286ccr51 \
            --branch-name main \
            --job-type RELEASE
