name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      AWS_INSTANCE_SG_ID: ${{secrets.AWS_INSTANCE_SG_ID}}
    steps:
      - name: Checkout code
        uses: actions/checkout@4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.EC2_DEPLOY_ROLE_ARN}}
          role-session-name: github-actions-deploy-cms-session
          aws-region: us-west-2
          
      - name: Whitelist runner ip address
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id $AWS_INSTANCE_SG_ID
            --protocol tcp \
            --port 22 \
            --cidr ${{steps.ip.outputs.ipv4}}/32
      - name: Zip the required files
        run: |
          zip -r cms.zip . -x node_modules/* -x ".git/*" -x "*.log" -x ".env" -x ".env.*" -x ".env.*.local" -x "sites/*" -x "!sites/cms/*"
