name: Deploy to EC2

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      AWS_INSTANCE_SG_ID: ${{secrets.AWS_INSTANCE_SG_ID}}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.EC2_DEPLOY_ROLE_ARN}}
          role-session-name: github-actions-deploy-cms-session
          aws-region: us-west-2
          
      - name: Get runner IP address
        id: ip
        uses: haythem/public-ip@v1.3
          
      - name: Whitelist GitHub action IP address
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id $AWS_INSTANCE_SG_ID \
            --protocol tcp \
            --port 22 \
            --cidr ${{steps.ip.outputs.ipv4}}/32
            
      - name: Add SSH Key
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1.4.1
        with:
          ssh-private-key: ${{secrets.EC2_SSH_PRIVATE_KEY}}
          ssh-host: ${{secrets.EC2_SERVER_HOST}}

      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Zip the required files
        run: |
          zip -r cms.zip . \
            -x node_modules/* \
            -x ".git/*" \
            -x "*.log" \
            -x ".env" \
            -x ".env.*" \
            -x ".env.*.local" \
            -x "sites/msb/*" \
            -x "packakages/*" \
      
      - name: Upload zipped repo to server
        run: |
          scp cms.zip ${{secrets.EC2_SERVER_USER}}@${{secrets.EC2_SERVER_HOST}}
          
      - name: Remove GitHub actions IP from security group
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id $AWS_INSTANCE_SG_ID \
            --protocol tcp \
            --port 22 \
            --cidr ${{steps.ip.outputs.ipv4}}/32
            
